sudo: false
branches:
  only:
  - master
language: android
jdk: oraclejdk8
cache:
 directories:
 -$HOME/.gradle/caches/
 -$HOME/.gradle/wrapper/
env:
 global:
 - ANDROID_API=27
 - ANDROID_BUILD_TOOLS=27.0.3
android:
  components:
  - tools
  - platform-tools
  - extra-android-support
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - android-$ANDROID_API_LEVEL
  - build-tools-$ANDROID_BUILD_TOOLS
  licenses:
  - ".+"
before_install:
- chmod +x gradlew
install:
- "./gradlew dependencies"
script:
- "./gradlew check"
after_failure:
- cat "$TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"