sudo: false
branches:
  only:
  - master
language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - extra-android-support
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - android-27
  - build-tools-27.0.3
  licenses:
  - ".+"
before_install:
- chmod +x gradlew
install:
- "./gradlew dependencies"
script:
- "./gradlew check"
after_failure:
- cat "$TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"